server:
  port: ${SERVER_PORT:8761}
eureka:
  server:
    enable-self-preservation: ${EUREKA_SERVER_ENABLESELFPRESERVATION:true}
    eviction-interval-timer-in-ms: 5000
    renewal-threshold-update-interval-ms: 120000
    use-read-only-response-cache: false
  instance:
    appname: ${spring.application.name}
    ip-address: ${EUREKA_INSTANCE_IPADDRESS:192.168.206.129}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFERIPADDRESS:true}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    healthcheck:
      enabled: ${EUREKA_CLIENT_HEALTHCHECK_ENABLED:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://192.168.206.128:8761/eureka/,http://192.168.206.129:8761/eureka/}

