spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.98.141.233:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: zjw@2020


mybatis:
  type-aliases-package: com.wei.oauth.domain
  configuration:
    map-underscore-to-camel-case: true
